apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: f5demo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: f5demo
        tier: frontend
    spec:
      containers:
      - name: f5demo
        image: kmunson1973/f5demo:1.0.0
        ports:
        - containerPort: 8080

